id: IE43E84C3
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T16:23:19+00:00'
last_modified: '2022-06-08T12:08:12.008282+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W24185
  title: ས་ལུགས་བསྐང་གསོའི་ཆོ་ག་དང་བསྟོད་པ་རྣམས་ཕྱོགས་གཅིག་ཏུ་བསྡེབས་པ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    FC75:
      image_group_id: I1CZ954
      title: ''
      total_pages: 68
      order: 1
      base_file: FC75.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
