id: P009594
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W24185
  title: ས་ལུགས་བསྐང་གསོའི་ཆོ་ག་དང་བསྟོད་པ་རྣམས་ཕྱོགས་གཅིག་ཏུ་བསྡེབས་པ
  author: ''
  volumes:
    4f3371097e624788b468be707fbb4957:
      image_group_id: I1CZ954
      title: ''
      volume_number: 1
      total_pages: 68
      base_file: v001.txt
